spring: # test profile
  profiles:
    active: default
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: "jdbc:h2:mem:Code2CV"
    username: "sa"
    password: ""
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true # SQL 포맷팅
        highlight_sql: true
  data:
    redis:
      host: localhost
      port: 6379
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 619abd8bd20ef8db831ea0ca834ebe4e
            #client-secret: <카카오 앱 시크릿 키> # 선택 사항
            redirect-uri: http://localhost:8080/oauth2/code/kakao
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - profile_image
              - account_email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
jwt:
  secret: devstesttesttesttesttesttesttesttest
  access-token-expire-time: 1800000 # 30 minutes
  refresh-token-expire-time: 2592000000 # 30 days

logging.level:
  org.hibernate:
    orm.jdbc.bind: trace
    SQL: debug

management:
  endpoints:
    web:
      exposure: # 외부에 노출할 엔드포인트
        include: prometheus, health, info
  metrics:
    tags:
      application: "finale" # 메트릭 데이터에 태그를 추가

cloud:
  aws:
    credentials:
      access-key: "access key"
      secret-key: "secret key"
    region:
      static: "us-east-1"
    s3:
      bucket: "finale2"